export const USER_LOGIN = 'USER_LOGIN'
export const USER_UPDATE_NAME = 'USER_UPDATE_NAME'
export const INIT_LOGIN = 'INIT_LOGIN'
export const USER_LOGOUT = 'USER_LOGOUT'
export const USER_REGISTER = 'USER_REGISTER'
export const USER_INFO = 'USER_INFO'


export const COMMON_COIN_LIST = 'COMMON_COIN_LIST'
export const COMMON_CONFIG_LIST = 'COMMON_CONFIG_LIST'




